### ISSUE TITLE
Crash on startup on dedicated servers 

### ISSUE THREAD

**Issue by superfluke** [SHsuperCM/Simply-Bedrock-Bedrock-Miner-#1]
Mod causes dedicated servers to crash on start-up with the error
`[Server thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber SHCM.SHsuperCM.simplybedrock.blocks.ModBlocks for modid simplybedrock
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer`
[Full crash log](https://paste.ubuntu.com/p/kfCJHNQtYv/)

Fixed the issue by adding @SideOnly(Side.CLIENT) to this method: https://github.com/SHsuperCM/Simply-Bedrock-Bedrock-Miner-/blob/d2b0c07e49776f938c3e173334d5a1e787bd6a63/src/main/java/SHCM/SHsuperCM/simplybedrock/blocks/ModBlocks.java#L48

Not sure if that's the proper way to do that, but seemed to get things running on the server.

**Comment by SHsuperCM** [comment]
Sorry for the long wait, Github didn't notify me of any issues.. Weird... I merged and will take a look at other things later and update on curse.. Thank you for making the PR!
