### ISSUE TITLE
Miner disappears when mined using 3x3 tool

### ISSUE THREAD

**Issue by lynaevm** [SHsuperCM/Simply-Bedrock-Bedrock-Miner-#2]
When the bedrock miner was mined by breaking a block next to it using a hammer, the miner disappeared and the block the hammer was centered on becomes a ghost block.  Using the hammer directly on the bedrock miner works fine.  This was done using a thermal expansion hammer (platinum to be specific), was observed on a stream and is repeatable.

Heres a clip of the problem happening.

https://clips.twitch.tv/UnsightlyObeseDoveHeyGuys

**Comment by SHsuperCM** [comment]
Sorry for the long wait, Github didn't notify me of any issues.. Weird... I'mma take a look later..

**Comment by SHsuperCM** [comment]
As I thought, it was not a problem on Simply Bedrock but rather an issue on TiC hammers..
The code I use to drop the item from the block is the accepted way to make block drops in forge and it seems as if TiC didnt use that within the hammer..

Anyways, it seems as if TiC fixed it(tested with TConstruct-1.12.2-2.12.0.115)
